// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package com.cloudzero.arch.pb;

public interface CloudResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CloudResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *应答码 [必须]
   * </pre>
   *
   * <code>string returnCode = 1;</code>
   */
  java.lang.String getReturnCode();
  /**
   * <pre>
   *应答码 [必须]
   * </pre>
   *
   * <code>string returnCode = 1;</code>
   */
  com.google.protobuf.ByteString
      getReturnCodeBytes();

  /**
   * <pre>
   *简短描述 [可选]
   * </pre>
   *
   * <code>string description = 2;</code>
   */
  java.lang.String getDescription();
  /**
   * <pre>
   *简短描述 [可选]
   * </pre>
   *
   * <code>string description = 2;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <pre>
   *响应消息体 [可选]
   * </pre>
   *
   * <code>.google.protobuf.Any body = 21;</code>
   */
  boolean hasBody();
  /**
   * <pre>
   *响应消息体 [可选]
   * </pre>
   *
   * <code>.google.protobuf.Any body = 21;</code>
   */
  com.google.protobuf.Any getBody();
  /**
   * <pre>
   *响应消息体 [可选]
   * </pre>
   *
   * <code>.google.protobuf.Any body = 21;</code>
   */
  com.google.protobuf.AnyOrBuilder getBodyOrBuilder();
}
