// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package com.cloudzero.arch.pb;

/**
 * <pre>
 *请求协议
 * </pre>
 *
 * Protobuf type {@code CloudRequest}
 */
public  final class CloudRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CloudRequest)
    CloudRequestOrBuilder {
  // Use CloudRequest.newBuilder() to construct.
  private CloudRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CloudRequest() {
    ngLabel_ = "";
    ngVersion_ = "";
    action_ = "";
    actVersion_ = "";
    platform_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private CloudRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            ngLabel_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            ngVersion_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            action_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            actVersion_ = s;
            break;
          }
          case 40: {
            int rawValue = input.readEnum();

            platform_ = rawValue;
            break;
          }
          case 170: {
            com.google.protobuf.Any.Builder subBuilder = null;
            if (body_ != null) {
              subBuilder = body_.toBuilder();
            }
            body_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(body_);
              body_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cloudzero.arch.pb.Proto.internal_static_CloudRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cloudzero.arch.pb.Proto.internal_static_CloudRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cloudzero.arch.pb.CloudRequest.class, com.cloudzero.arch.pb.CloudRequest.Builder.class);
  }

  /**
   * Protobuf enum {@code CloudRequest.Platform}
   */
  public enum Platform
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Unknown = 0;</code>
     */
    Unknown(0),
    /**
     * <code>Android = 1;</code>
     */
    Android(1),
    /**
     * <code>Ios = 2;</code>
     */
    Ios(2),
    /**
     * <code>Weixin = 3;</code>
     */
    Weixin(3),
    /**
     * <code>Web = 4;</code>
     */
    Web(4),
    /**
     * <code>Phone = 5;</code>
     */
    Phone(5),
    /**
     * <code>Sms = 6;</code>
     */
    Sms(6),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Unknown = 0;</code>
     */
    public static final int Unknown_VALUE = 0;
    /**
     * <code>Android = 1;</code>
     */
    public static final int Android_VALUE = 1;
    /**
     * <code>Ios = 2;</code>
     */
    public static final int Ios_VALUE = 2;
    /**
     * <code>Weixin = 3;</code>
     */
    public static final int Weixin_VALUE = 3;
    /**
     * <code>Web = 4;</code>
     */
    public static final int Web_VALUE = 4;
    /**
     * <code>Phone = 5;</code>
     */
    public static final int Phone_VALUE = 5;
    /**
     * <code>Sms = 6;</code>
     */
    public static final int Sms_VALUE = 6;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Platform valueOf(int value) {
      return forNumber(value);
    }

    public static Platform forNumber(int value) {
      switch (value) {
        case 0: return Unknown;
        case 1: return Android;
        case 2: return Ios;
        case 3: return Weixin;
        case 4: return Web;
        case 5: return Phone;
        case 6: return Sms;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Platform>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Platform> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Platform>() {
            public Platform findValueByNumber(int number) {
              return Platform.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.cloudzero.arch.pb.CloudRequest.getDescriptor().getEnumTypes().get(0);
    }

    private static final Platform[] VALUES = values();

    public static Platform valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Platform(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:CloudRequest.Platform)
  }

  public static final int NGLABEL_FIELD_NUMBER = 1;
  private volatile java.lang.Object ngLabel_;
  /**
   * <pre>
   *处理请求的单元的标签 [必须]
   * </pre>
   *
   * <code>string ngLabel = 1;</code>
   */
  public java.lang.String getNgLabel() {
    java.lang.Object ref = ngLabel_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ngLabel_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *处理请求的单元的标签 [必须]
   * </pre>
   *
   * <code>string ngLabel = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNgLabelBytes() {
    java.lang.Object ref = ngLabel_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ngLabel_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NGVERSION_FIELD_NUMBER = 2;
  private volatile java.lang.Object ngVersion_;
  /**
   * <pre>
   *处理请求的单元的版本 [必须]
   * </pre>
   *
   * <code>string ngVersion = 2;</code>
   */
  public java.lang.String getNgVersion() {
    java.lang.Object ref = ngVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ngVersion_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *处理请求的单元的版本 [必须]
   * </pre>
   *
   * <code>string ngVersion = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNgVersionBytes() {
    java.lang.Object ref = ngVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ngVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACTION_FIELD_NUMBER = 3;
  private volatile java.lang.Object action_;
  /**
   * <pre>
   *请求动作描述 [必须]
   * </pre>
   *
   * <code>string action = 3;</code>
   */
  public java.lang.String getAction() {
    java.lang.Object ref = action_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      action_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *请求动作描述 [必须]
   * </pre>
   *
   * <code>string action = 3;</code>
   */
  public com.google.protobuf.ByteString
      getActionBytes() {
    java.lang.Object ref = action_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      action_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACTVERSION_FIELD_NUMBER = 4;
  private volatile java.lang.Object actVersion_;
  /**
   * <pre>
   *动作版本 [必须]
   * </pre>
   *
   * <code>string actVersion = 4;</code>
   */
  public java.lang.String getActVersion() {
    java.lang.Object ref = actVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      actVersion_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *动作版本 [必须]
   * </pre>
   *
   * <code>string actVersion = 4;</code>
   */
  public com.google.protobuf.ByteString
      getActVersionBytes() {
    java.lang.Object ref = actVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      actVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PLATFORM_FIELD_NUMBER = 5;
  private int platform_;
  /**
   * <pre>
   *请求发送平台的类型
   * </pre>
   *
   * <code>.CloudRequest.Platform platform = 5;</code>
   */
  public int getPlatformValue() {
    return platform_;
  }
  /**
   * <pre>
   *请求发送平台的类型
   * </pre>
   *
   * <code>.CloudRequest.Platform platform = 5;</code>
   */
  public com.cloudzero.arch.pb.CloudRequest.Platform getPlatform() {
    com.cloudzero.arch.pb.CloudRequest.Platform result = com.cloudzero.arch.pb.CloudRequest.Platform.valueOf(platform_);
    return result == null ? com.cloudzero.arch.pb.CloudRequest.Platform.UNRECOGNIZED : result;
  }

  public static final int BODY_FIELD_NUMBER = 21;
  private com.google.protobuf.Any body_;
  /**
   * <pre>
   *请求消息体 [可选]
   * </pre>
   *
   * <code>.google.protobuf.Any body = 21;</code>
   */
  public boolean hasBody() {
    return body_ != null;
  }
  /**
   * <pre>
   *请求消息体 [可选]
   * </pre>
   *
   * <code>.google.protobuf.Any body = 21;</code>
   */
  public com.google.protobuf.Any getBody() {
    return body_ == null ? com.google.protobuf.Any.getDefaultInstance() : body_;
  }
  /**
   * <pre>
   *请求消息体 [可选]
   * </pre>
   *
   * <code>.google.protobuf.Any body = 21;</code>
   */
  public com.google.protobuf.AnyOrBuilder getBodyOrBuilder() {
    return getBody();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNgLabelBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ngLabel_);
    }
    if (!getNgVersionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ngVersion_);
    }
    if (!getActionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, action_);
    }
    if (!getActVersionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, actVersion_);
    }
    if (platform_ != com.cloudzero.arch.pb.CloudRequest.Platform.Unknown.getNumber()) {
      output.writeEnum(5, platform_);
    }
    if (body_ != null) {
      output.writeMessage(21, getBody());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNgLabelBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ngLabel_);
    }
    if (!getNgVersionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ngVersion_);
    }
    if (!getActionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, action_);
    }
    if (!getActVersionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, actVersion_);
    }
    if (platform_ != com.cloudzero.arch.pb.CloudRequest.Platform.Unknown.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, platform_);
    }
    if (body_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(21, getBody());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cloudzero.arch.pb.CloudRequest)) {
      return super.equals(obj);
    }
    com.cloudzero.arch.pb.CloudRequest other = (com.cloudzero.arch.pb.CloudRequest) obj;

    boolean result = true;
    result = result && getNgLabel()
        .equals(other.getNgLabel());
    result = result && getNgVersion()
        .equals(other.getNgVersion());
    result = result && getAction()
        .equals(other.getAction());
    result = result && getActVersion()
        .equals(other.getActVersion());
    result = result && platform_ == other.platform_;
    result = result && (hasBody() == other.hasBody());
    if (hasBody()) {
      result = result && getBody()
          .equals(other.getBody());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NGLABEL_FIELD_NUMBER;
    hash = (53 * hash) + getNgLabel().hashCode();
    hash = (37 * hash) + NGVERSION_FIELD_NUMBER;
    hash = (53 * hash) + getNgVersion().hashCode();
    hash = (37 * hash) + ACTION_FIELD_NUMBER;
    hash = (53 * hash) + getAction().hashCode();
    hash = (37 * hash) + ACTVERSION_FIELD_NUMBER;
    hash = (53 * hash) + getActVersion().hashCode();
    hash = (37 * hash) + PLATFORM_FIELD_NUMBER;
    hash = (53 * hash) + platform_;
    if (hasBody()) {
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cloudzero.arch.pb.CloudRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cloudzero.arch.pb.CloudRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cloudzero.arch.pb.CloudRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cloudzero.arch.pb.CloudRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cloudzero.arch.pb.CloudRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cloudzero.arch.pb.CloudRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cloudzero.arch.pb.CloudRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cloudzero.arch.pb.CloudRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cloudzero.arch.pb.CloudRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.cloudzero.arch.pb.CloudRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cloudzero.arch.pb.CloudRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cloudzero.arch.pb.CloudRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cloudzero.arch.pb.CloudRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *请求协议
   * </pre>
   *
   * Protobuf type {@code CloudRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CloudRequest)
      com.cloudzero.arch.pb.CloudRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cloudzero.arch.pb.Proto.internal_static_CloudRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cloudzero.arch.pb.Proto.internal_static_CloudRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cloudzero.arch.pb.CloudRequest.class, com.cloudzero.arch.pb.CloudRequest.Builder.class);
    }

    // Construct using com.cloudzero.arch.pb.CloudRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      ngLabel_ = "";

      ngVersion_ = "";

      action_ = "";

      actVersion_ = "";

      platform_ = 0;

      if (bodyBuilder_ == null) {
        body_ = null;
      } else {
        body_ = null;
        bodyBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cloudzero.arch.pb.Proto.internal_static_CloudRequest_descriptor;
    }

    public com.cloudzero.arch.pb.CloudRequest getDefaultInstanceForType() {
      return com.cloudzero.arch.pb.CloudRequest.getDefaultInstance();
    }

    public com.cloudzero.arch.pb.CloudRequest build() {
      com.cloudzero.arch.pb.CloudRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.cloudzero.arch.pb.CloudRequest buildPartial() {
      com.cloudzero.arch.pb.CloudRequest result = new com.cloudzero.arch.pb.CloudRequest(this);
      result.ngLabel_ = ngLabel_;
      result.ngVersion_ = ngVersion_;
      result.action_ = action_;
      result.actVersion_ = actVersion_;
      result.platform_ = platform_;
      if (bodyBuilder_ == null) {
        result.body_ = body_;
      } else {
        result.body_ = bodyBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cloudzero.arch.pb.CloudRequest) {
        return mergeFrom((com.cloudzero.arch.pb.CloudRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cloudzero.arch.pb.CloudRequest other) {
      if (other == com.cloudzero.arch.pb.CloudRequest.getDefaultInstance()) return this;
      if (!other.getNgLabel().isEmpty()) {
        ngLabel_ = other.ngLabel_;
        onChanged();
      }
      if (!other.getNgVersion().isEmpty()) {
        ngVersion_ = other.ngVersion_;
        onChanged();
      }
      if (!other.getAction().isEmpty()) {
        action_ = other.action_;
        onChanged();
      }
      if (!other.getActVersion().isEmpty()) {
        actVersion_ = other.actVersion_;
        onChanged();
      }
      if (other.platform_ != 0) {
        setPlatformValue(other.getPlatformValue());
      }
      if (other.hasBody()) {
        mergeBody(other.getBody());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.cloudzero.arch.pb.CloudRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.cloudzero.arch.pb.CloudRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object ngLabel_ = "";
    /**
     * <pre>
     *处理请求的单元的标签 [必须]
     * </pre>
     *
     * <code>string ngLabel = 1;</code>
     */
    public java.lang.String getNgLabel() {
      java.lang.Object ref = ngLabel_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ngLabel_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *处理请求的单元的标签 [必须]
     * </pre>
     *
     * <code>string ngLabel = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNgLabelBytes() {
      java.lang.Object ref = ngLabel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ngLabel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *处理请求的单元的标签 [必须]
     * </pre>
     *
     * <code>string ngLabel = 1;</code>
     */
    public Builder setNgLabel(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ngLabel_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *处理请求的单元的标签 [必须]
     * </pre>
     *
     * <code>string ngLabel = 1;</code>
     */
    public Builder clearNgLabel() {
      
      ngLabel_ = getDefaultInstance().getNgLabel();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *处理请求的单元的标签 [必须]
     * </pre>
     *
     * <code>string ngLabel = 1;</code>
     */
    public Builder setNgLabelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ngLabel_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object ngVersion_ = "";
    /**
     * <pre>
     *处理请求的单元的版本 [必须]
     * </pre>
     *
     * <code>string ngVersion = 2;</code>
     */
    public java.lang.String getNgVersion() {
      java.lang.Object ref = ngVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ngVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *处理请求的单元的版本 [必须]
     * </pre>
     *
     * <code>string ngVersion = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNgVersionBytes() {
      java.lang.Object ref = ngVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ngVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *处理请求的单元的版本 [必须]
     * </pre>
     *
     * <code>string ngVersion = 2;</code>
     */
    public Builder setNgVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ngVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *处理请求的单元的版本 [必须]
     * </pre>
     *
     * <code>string ngVersion = 2;</code>
     */
    public Builder clearNgVersion() {
      
      ngVersion_ = getDefaultInstance().getNgVersion();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *处理请求的单元的版本 [必须]
     * </pre>
     *
     * <code>string ngVersion = 2;</code>
     */
    public Builder setNgVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ngVersion_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object action_ = "";
    /**
     * <pre>
     *请求动作描述 [必须]
     * </pre>
     *
     * <code>string action = 3;</code>
     */
    public java.lang.String getAction() {
      java.lang.Object ref = action_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        action_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *请求动作描述 [必须]
     * </pre>
     *
     * <code>string action = 3;</code>
     */
    public com.google.protobuf.ByteString
        getActionBytes() {
      java.lang.Object ref = action_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        action_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *请求动作描述 [必须]
     * </pre>
     *
     * <code>string action = 3;</code>
     */
    public Builder setAction(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      action_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *请求动作描述 [必须]
     * </pre>
     *
     * <code>string action = 3;</code>
     */
    public Builder clearAction() {
      
      action_ = getDefaultInstance().getAction();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *请求动作描述 [必须]
     * </pre>
     *
     * <code>string action = 3;</code>
     */
    public Builder setActionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      action_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object actVersion_ = "";
    /**
     * <pre>
     *动作版本 [必须]
     * </pre>
     *
     * <code>string actVersion = 4;</code>
     */
    public java.lang.String getActVersion() {
      java.lang.Object ref = actVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        actVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *动作版本 [必须]
     * </pre>
     *
     * <code>string actVersion = 4;</code>
     */
    public com.google.protobuf.ByteString
        getActVersionBytes() {
      java.lang.Object ref = actVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        actVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *动作版本 [必须]
     * </pre>
     *
     * <code>string actVersion = 4;</code>
     */
    public Builder setActVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      actVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *动作版本 [必须]
     * </pre>
     *
     * <code>string actVersion = 4;</code>
     */
    public Builder clearActVersion() {
      
      actVersion_ = getDefaultInstance().getActVersion();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *动作版本 [必须]
     * </pre>
     *
     * <code>string actVersion = 4;</code>
     */
    public Builder setActVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      actVersion_ = value;
      onChanged();
      return this;
    }

    private int platform_ = 0;
    /**
     * <pre>
     *请求发送平台的类型
     * </pre>
     *
     * <code>.CloudRequest.Platform platform = 5;</code>
     */
    public int getPlatformValue() {
      return platform_;
    }
    /**
     * <pre>
     *请求发送平台的类型
     * </pre>
     *
     * <code>.CloudRequest.Platform platform = 5;</code>
     */
    public Builder setPlatformValue(int value) {
      platform_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *请求发送平台的类型
     * </pre>
     *
     * <code>.CloudRequest.Platform platform = 5;</code>
     */
    public com.cloudzero.arch.pb.CloudRequest.Platform getPlatform() {
      com.cloudzero.arch.pb.CloudRequest.Platform result = com.cloudzero.arch.pb.CloudRequest.Platform.valueOf(platform_);
      return result == null ? com.cloudzero.arch.pb.CloudRequest.Platform.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *请求发送平台的类型
     * </pre>
     *
     * <code>.CloudRequest.Platform platform = 5;</code>
     */
    public Builder setPlatform(com.cloudzero.arch.pb.CloudRequest.Platform value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      platform_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *请求发送平台的类型
     * </pre>
     *
     * <code>.CloudRequest.Platform platform = 5;</code>
     */
    public Builder clearPlatform() {
      
      platform_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Any body_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> bodyBuilder_;
    /**
     * <pre>
     *请求消息体 [可选]
     * </pre>
     *
     * <code>.google.protobuf.Any body = 21;</code>
     */
    public boolean hasBody() {
      return bodyBuilder_ != null || body_ != null;
    }
    /**
     * <pre>
     *请求消息体 [可选]
     * </pre>
     *
     * <code>.google.protobuf.Any body = 21;</code>
     */
    public com.google.protobuf.Any getBody() {
      if (bodyBuilder_ == null) {
        return body_ == null ? com.google.protobuf.Any.getDefaultInstance() : body_;
      } else {
        return bodyBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *请求消息体 [可选]
     * </pre>
     *
     * <code>.google.protobuf.Any body = 21;</code>
     */
    public Builder setBody(com.google.protobuf.Any value) {
      if (bodyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
        onChanged();
      } else {
        bodyBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *请求消息体 [可选]
     * </pre>
     *
     * <code>.google.protobuf.Any body = 21;</code>
     */
    public Builder setBody(
        com.google.protobuf.Any.Builder builderForValue) {
      if (bodyBuilder_ == null) {
        body_ = builderForValue.build();
        onChanged();
      } else {
        bodyBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *请求消息体 [可选]
     * </pre>
     *
     * <code>.google.protobuf.Any body = 21;</code>
     */
    public Builder mergeBody(com.google.protobuf.Any value) {
      if (bodyBuilder_ == null) {
        if (body_ != null) {
          body_ =
            com.google.protobuf.Any.newBuilder(body_).mergeFrom(value).buildPartial();
        } else {
          body_ = value;
        }
        onChanged();
      } else {
        bodyBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *请求消息体 [可选]
     * </pre>
     *
     * <code>.google.protobuf.Any body = 21;</code>
     */
    public Builder clearBody() {
      if (bodyBuilder_ == null) {
        body_ = null;
        onChanged();
      } else {
        body_ = null;
        bodyBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *请求消息体 [可选]
     * </pre>
     *
     * <code>.google.protobuf.Any body = 21;</code>
     */
    public com.google.protobuf.Any.Builder getBodyBuilder() {
      
      onChanged();
      return getBodyFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *请求消息体 [可选]
     * </pre>
     *
     * <code>.google.protobuf.Any body = 21;</code>
     */
    public com.google.protobuf.AnyOrBuilder getBodyOrBuilder() {
      if (bodyBuilder_ != null) {
        return bodyBuilder_.getMessageOrBuilder();
      } else {
        return body_ == null ?
            com.google.protobuf.Any.getDefaultInstance() : body_;
      }
    }
    /**
     * <pre>
     *请求消息体 [可选]
     * </pre>
     *
     * <code>.google.protobuf.Any body = 21;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
        getBodyFieldBuilder() {
      if (bodyBuilder_ == null) {
        bodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                getBody(),
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      return bodyBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:CloudRequest)
  }

  // @@protoc_insertion_point(class_scope:CloudRequest)
  private static final com.cloudzero.arch.pb.CloudRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cloudzero.arch.pb.CloudRequest();
  }

  public static com.cloudzero.arch.pb.CloudRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CloudRequest>
      PARSER = new com.google.protobuf.AbstractParser<CloudRequest>() {
    public CloudRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new CloudRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CloudRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CloudRequest> getParserForType() {
    return PARSER;
  }

  public com.cloudzero.arch.pb.CloudRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

