// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package com.cloudzero.arch.pb;

public final class Proto {
  private Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CloudRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CloudRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CloudResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CloudResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Void_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Void_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016protocol.proto\032\031google/protobuf/any.pr" +
      "oto\"\202\002\n\014CloudRequest\022\017\n\007ngLabel\030\001 \001(\t\022\021\n" +
      "\tngVersion\030\002 \001(\t\022\016\n\006action\030\003 \001(\t\022\022\n\nactV" +
      "ersion\030\004 \001(\t\022(\n\010platform\030\005 \001(\0162\026.CloudRe" +
      "quest.Platform\022\"\n\004body\030\025 \001(\0132\024.google.pr" +
      "otobuf.Any\"V\n\010Platform\022\013\n\007Unknown\020\000\022\013\n\007A" +
      "ndroid\020\001\022\007\n\003Ios\020\002\022\n\n\006Weixin\020\003\022\007\n\003Web\020\004\022\t" +
      "\n\005Phone\020\005\022\007\n\003Sms\020\006J\004\010\006\020\025\"b\n\rCloudRespons" +
      "e\022\022\n\nreturnCode\030\001 \001(\t\022\023\n\013description\030\002 \001" +
      "(\t\022\"\n\004body\030\025 \001(\0132\024.google.protobuf.AnyJ\004",
      "\010\006\020\025\"\006\n\004VoidB \n\025com.cloudzero.arch.pbB\005P" +
      "rotoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_CloudRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CloudRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CloudRequest_descriptor,
        new java.lang.String[] { "NgLabel", "NgVersion", "Action", "ActVersion", "Platform", "Body", });
    internal_static_CloudResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CloudResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CloudResponse_descriptor,
        new java.lang.String[] { "ReturnCode", "Description", "Body", });
    internal_static_Void_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Void_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Void_descriptor,
        new java.lang.String[] { });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
