// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package com.cloudzero.arch.pb;

public interface VoidOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Void)
    com.google.protobuf.MessageOrBuilder {
}
