// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `interface.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.cloudzero.arch.ice.generate;

public abstract class Callback_DIceCaller_invoke
    extends IceInternal.TwowayCallback implements Ice.TwowayCallbackArg1<com.cloudzero.arch.pb.CloudResponse>
{
    public final void __completed(Ice.AsyncResult __result)
    {
        DIceCallerPrxHelper.__invoke_completed(this, __result);
    }
}
