// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `interface.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.cloudzero.arch.ice.generate;

public final class DIceCallerHolder extends Ice.ObjectHolderBase<DIceCaller>
{
    public
    DIceCallerHolder()
    {
    }

    public
    DIceCallerHolder(DIceCaller value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof DIceCaller)
        {
            value = (DIceCaller)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return _DIceCallerDisp.ice_staticId();
    }
}
