// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `interface.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.cloudzero.arch.ice.generate;

public final class DIceCallerI extends _DIceCallerDisp
{
    public
    DIceCallerI()
    {
    }

    public void
    call(com.cloudzero.arch.pb.CloudRequest request, Ice.Current __current)
    {
    }

    public com.cloudzero.arch.pb.CloudResponse
    invoke(com.cloudzero.arch.pb.CloudRequest request, Ice.Current __current)
    {
        return null;
    }
}
