// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `interface.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.cloudzero.arch.ice.generate;

public interface DIceCaller extends Ice.Object,
                                    _DIceCallerOperations, _DIceCallerOperationsNC
{
    public static final String ice_staticId = "::generate::DIceCaller";

    public static final long serialVersionUID = 517449864L;
}
