// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `interface.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.cloudzero.arch.ice.generate;

public interface DIceCallerPrx extends Ice.ObjectPrx
{
    public void call(com.cloudzero.arch.pb.CloudRequest request);

    public void call(com.cloudzero.arch.pb.CloudRequest request, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_call(com.cloudzero.arch.pb.CloudRequest request);

    public Ice.AsyncResult begin_call(com.cloudzero.arch.pb.CloudRequest request, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_call(com.cloudzero.arch.pb.CloudRequest request, Ice.Callback __cb);

    public Ice.AsyncResult begin_call(com.cloudzero.arch.pb.CloudRequest request, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_call(com.cloudzero.arch.pb.CloudRequest request, Callback_DIceCaller_call __cb);

    public Ice.AsyncResult begin_call(com.cloudzero.arch.pb.CloudRequest request, java.util.Map<String, String> __ctx, Callback_DIceCaller_call __cb);

    public Ice.AsyncResult begin_call(com.cloudzero.arch.pb.CloudRequest request, 
                                      IceInternal.Functional_VoidCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_call(com.cloudzero.arch.pb.CloudRequest request, 
                                      IceInternal.Functional_VoidCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                      IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_call(com.cloudzero.arch.pb.CloudRequest request, 
                                      java.util.Map<String, String> __ctx, 
                                      IceInternal.Functional_VoidCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_call(com.cloudzero.arch.pb.CloudRequest request, 
                                      java.util.Map<String, String> __ctx, 
                                      IceInternal.Functional_VoidCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                      IceInternal.Functional_BoolCallback __sentCb);

    public void end_call(Ice.AsyncResult __result);

    public com.cloudzero.arch.pb.CloudResponse invoke(com.cloudzero.arch.pb.CloudRequest request);

    public com.cloudzero.arch.pb.CloudResponse invoke(com.cloudzero.arch.pb.CloudRequest request, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_invoke(com.cloudzero.arch.pb.CloudRequest request);

    public Ice.AsyncResult begin_invoke(com.cloudzero.arch.pb.CloudRequest request, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_invoke(com.cloudzero.arch.pb.CloudRequest request, Ice.Callback __cb);

    public Ice.AsyncResult begin_invoke(com.cloudzero.arch.pb.CloudRequest request, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_invoke(com.cloudzero.arch.pb.CloudRequest request, Callback_DIceCaller_invoke __cb);

    public Ice.AsyncResult begin_invoke(com.cloudzero.arch.pb.CloudRequest request, java.util.Map<String, String> __ctx, Callback_DIceCaller_invoke __cb);

    public Ice.AsyncResult begin_invoke(com.cloudzero.arch.pb.CloudRequest request, 
                                        IceInternal.Functional_GenericCallback1<com.cloudzero.arch.pb.CloudResponse> __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_invoke(com.cloudzero.arch.pb.CloudRequest request, 
                                        IceInternal.Functional_GenericCallback1<com.cloudzero.arch.pb.CloudResponse> __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_invoke(com.cloudzero.arch.pb.CloudRequest request, 
                                        java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_GenericCallback1<com.cloudzero.arch.pb.CloudResponse> __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_invoke(com.cloudzero.arch.pb.CloudRequest request, 
                                        java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_GenericCallback1<com.cloudzero.arch.pb.CloudResponse> __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb);

    public com.cloudzero.arch.pb.CloudResponse end_invoke(Ice.AsyncResult __result);
}
