// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `interface.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.cloudzero.arch.ice.generate;

/**
 * Provides type-specific helper functions.
 **/
public final class DIceCallerPrxHelper extends Ice.ObjectPrxHelperBase implements DIceCallerPrx
{
    private static final String __call_name = "call";

    public void call(com.cloudzero.arch.pb.CloudRequest request)
    {
        call(request, null, false);
    }

    public void call(com.cloudzero.arch.pb.CloudRequest request, java.util.Map<String, String> __ctx)
    {
        call(request, __ctx, true);
    }

    private void call(com.cloudzero.arch.pb.CloudRequest request, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        end_call(begin_call(request, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_call(com.cloudzero.arch.pb.CloudRequest request)
    {
        return begin_call(request, null, false, false, null);
    }

    public Ice.AsyncResult begin_call(com.cloudzero.arch.pb.CloudRequest request, java.util.Map<String, String> __ctx)
    {
        return begin_call(request, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_call(com.cloudzero.arch.pb.CloudRequest request, Ice.Callback __cb)
    {
        return begin_call(request, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_call(com.cloudzero.arch.pb.CloudRequest request, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_call(request, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_call(com.cloudzero.arch.pb.CloudRequest request, Callback_DIceCaller_call __cb)
    {
        return begin_call(request, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_call(com.cloudzero.arch.pb.CloudRequest request, java.util.Map<String, String> __ctx, Callback_DIceCaller_call __cb)
    {
        return begin_call(request, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_call(com.cloudzero.arch.pb.CloudRequest request, 
                                      IceInternal.Functional_VoidCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_call(request, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_call(com.cloudzero.arch.pb.CloudRequest request, 
                                      IceInternal.Functional_VoidCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                      IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_call(request, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_call(com.cloudzero.arch.pb.CloudRequest request, 
                                      java.util.Map<String, String> __ctx, 
                                      IceInternal.Functional_VoidCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_call(request, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_call(com.cloudzero.arch.pb.CloudRequest request, 
                                      java.util.Map<String, String> __ctx, 
                                      IceInternal.Functional_VoidCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                      IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_call(request, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_call(com.cloudzero.arch.pb.CloudRequest request, 
                                       java.util.Map<String, String> __ctx, 
                                       boolean __explicitCtx, 
                                       boolean __synchronous, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_call(request, 
                          __ctx, 
                          __explicitCtx, 
                          __synchronous, 
                          new IceInternal.Functional_OnewayCallback(__responseCb, __exceptionCb, __sentCb));
    }

    private Ice.AsyncResult begin_call(com.cloudzero.arch.pb.CloudRequest request, 
                                       java.util.Map<String, String> __ctx, 
                                       boolean __explicitCtx, 
                                       boolean __synchronous, 
                                       IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__call_name, __cb);
        try
        {
            __result.prepare(__call_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            if(!request.isInitialized())
            {
                throw new Ice.MarshalException("type not fully initialized");
            }
            __os.writeByteSeq(request.toByteArray());
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public void end_call(Ice.AsyncResult __iresult)
    {
        __end(__iresult, __call_name);
    }

    private static final String __invoke_name = "invoke";

    public com.cloudzero.arch.pb.CloudResponse invoke(com.cloudzero.arch.pb.CloudRequest request)
    {
        return invoke(request, null, false);
    }

    public com.cloudzero.arch.pb.CloudResponse invoke(com.cloudzero.arch.pb.CloudRequest request, java.util.Map<String, String> __ctx)
    {
        return invoke(request, __ctx, true);
    }

    private com.cloudzero.arch.pb.CloudResponse invoke(com.cloudzero.arch.pb.CloudRequest request, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__invoke_name);
        return end_invoke(begin_invoke(request, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_invoke(com.cloudzero.arch.pb.CloudRequest request)
    {
        return begin_invoke(request, null, false, false, null);
    }

    public Ice.AsyncResult begin_invoke(com.cloudzero.arch.pb.CloudRequest request, java.util.Map<String, String> __ctx)
    {
        return begin_invoke(request, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_invoke(com.cloudzero.arch.pb.CloudRequest request, Ice.Callback __cb)
    {
        return begin_invoke(request, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_invoke(com.cloudzero.arch.pb.CloudRequest request, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_invoke(request, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_invoke(com.cloudzero.arch.pb.CloudRequest request, Callback_DIceCaller_invoke __cb)
    {
        return begin_invoke(request, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_invoke(com.cloudzero.arch.pb.CloudRequest request, java.util.Map<String, String> __ctx, Callback_DIceCaller_invoke __cb)
    {
        return begin_invoke(request, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_invoke(com.cloudzero.arch.pb.CloudRequest request, 
                                        IceInternal.Functional_GenericCallback1<com.cloudzero.arch.pb.CloudResponse> __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_invoke(request, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_invoke(com.cloudzero.arch.pb.CloudRequest request, 
                                        IceInternal.Functional_GenericCallback1<com.cloudzero.arch.pb.CloudResponse> __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_invoke(request, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_invoke(com.cloudzero.arch.pb.CloudRequest request, 
                                        java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_GenericCallback1<com.cloudzero.arch.pb.CloudResponse> __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_invoke(request, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_invoke(com.cloudzero.arch.pb.CloudRequest request, 
                                        java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_GenericCallback1<com.cloudzero.arch.pb.CloudResponse> __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_invoke(request, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_invoke(com.cloudzero.arch.pb.CloudRequest request, 
                                         java.util.Map<String, String> __ctx, 
                                         boolean __explicitCtx, 
                                         boolean __synchronous, 
                                         IceInternal.Functional_GenericCallback1<com.cloudzero.arch.pb.CloudResponse> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_invoke(request, __ctx, __explicitCtx, __synchronous, 
                            new IceInternal.Functional_TwowayCallbackArg1<com.cloudzero.arch.pb.CloudResponse>(__responseCb, __exceptionCb, __sentCb)
                                {
                                    public final void __completed(Ice.AsyncResult __result)
                                    {
                                        DIceCallerPrxHelper.__invoke_completed(this, __result);
                                    }
                                });
    }

    private Ice.AsyncResult begin_invoke(com.cloudzero.arch.pb.CloudRequest request, 
                                         java.util.Map<String, String> __ctx, 
                                         boolean __explicitCtx, 
                                         boolean __synchronous, 
                                         IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__invoke_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__invoke_name, __cb);
        try
        {
            __result.prepare(__invoke_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            if(!request.isInitialized())
            {
                throw new Ice.MarshalException("type not fully initialized");
            }
            __os.writeByteSeq(request.toByteArray());
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public com.cloudzero.arch.pb.CloudResponse end_invoke(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __invoke_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            com.cloudzero.arch.pb.CloudResponse __ret;
            try
            {
                __ret = com.cloudzero.arch.pb.CloudResponse.parseFrom(__is.readByteSeq());
            }
            catch(com.google.protobuf.InvalidProtocolBufferException __ex)
            {
                throw new Ice.MarshalException(__ex);
            }
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __invoke_completed(Ice.TwowayCallbackArg1<com.cloudzero.arch.pb.CloudResponse> __cb, Ice.AsyncResult __result)
    {
        com.cloudzero.arch.ice.generate.DIceCallerPrx __proxy = (com.cloudzero.arch.ice.generate.DIceCallerPrx)__result.getProxy();
        com.cloudzero.arch.pb.CloudResponse __ret = null;
        try
        {
            __ret = __proxy.end_invoke(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static DIceCallerPrx checkedCast(Ice.ObjectPrx __obj)
    {
        return checkedCastImpl(__obj, ice_staticId(), DIceCallerPrx.class, DIceCallerPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static DIceCallerPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __ctx, ice_staticId(), DIceCallerPrx.class, DIceCallerPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static DIceCallerPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return checkedCastImpl(__obj, __facet, ice_staticId(), DIceCallerPrx.class, DIceCallerPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static DIceCallerPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __facet, __ctx, ice_staticId(), DIceCallerPrx.class, DIceCallerPrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @return A proxy for this type.
     **/
    public static DIceCallerPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        return uncheckedCastImpl(__obj, DIceCallerPrx.class, DIceCallerPrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    public static DIceCallerPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return uncheckedCastImpl(__obj, __facet, DIceCallerPrx.class, DIceCallerPrxHelper.class);
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::generate::DIceCaller"
    };

    /**
     * Provides the Slice type ID of this type.
     * @return The Slice type ID.
     **/
    public static String ice_staticId()
    {
        return __ids[1];
    }

    public static void __write(IceInternal.BasicStream __os, DIceCallerPrx v)
    {
        __os.writeProxy(v);
    }

    public static DIceCallerPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            DIceCallerPrxHelper result = new DIceCallerPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
